### ISSUE TITLE
Question regarding the language specification about Sets

### ISSUE THREAD

**Issue by mjolivet-lucca** [biscuit-auth/biscuit#110]
In the [Specification](https://github.com/biscuit-auth/biscuit/blob/master/SPECIFICATIONS.md) there is a line about how sets should be formed : 

`<set> ::= "[" <sp>? ( <fact_term> ( <sp>? "," <sp>? <set_term>)* <sp>? )? "]"`

Is it normal to have a `fact_term` at the beginning ? it would mean that sets can contain sets, followed by set terms, but not successions of sets.

I wonder if it's a typo, and if it should be a `set_term` instead.

What is your opinion on the matter ?

**Comment by divarvel** [comment]
It looks like a mistake.

**Comment by Geal** [comment]
fixed by #111
