### ISSUE TITLE
separate v2 and v3 samples

### ISSUE THREAD

**Issue by Geal** [biscuit-auth/biscuit#114]
in https://github.com/biscuit-auth/biscuit/commit/10863a0789aca45f30554702ed3775864abedd8e we put the samples with version 3 in `samples/v2`. And with 3rd party tokens, we will move to version 4. We should separate them in different directories

**Comment by divarvel** [comment]
we could split things. for now v2 is more a spec-level version, since blocks v3 and v4 can coexist within tokens (and v2 blocks are deprecated).
