### ISSUE TITLE
Purpose of the `Parens` op

### ISSUE THREAD

**Issue by arnsholt** [biscuit-auth/biscuit#133]
(This one is less concrete than my previous issue, so if there's a more appropriate forum for this kind of discussion I apologize, but I couldn't find mention of anything on the homepage)

I'm a bit confused as to the Parens op in the expression format, isn't it just a noop? I can see an argument for it were important to reconstitute the concrete syntax used to create an expression and differentiate `1 + (2 * 3)` and `1 + 2 * 3` which otherwise would have the same abstract syntax, but I'm not sure that's an important consideration here; one of the benefits of RPN (which is a solution I really dig here!) is precisely that you don't need parens: different infix operator orders give distinct stacks.

**Comment by Geal** [comment]
IIRC the point was to reconstruct the same expression when displaying it. While it's not a concern for execution, error messages print the failing check so they should be consistent with how they were written
