### ISSUE TITLE
length() on strings

### ISSUE THREAD

**Issue by yaronf** [biscuit-auth/biscuit#158]
This operator returns the byte length of the string (rather than the number of Unicode runes, which would be the Java way). Please clarify it in the Specification.

**Comment by divarvel** [comment]
Indeed, the best behaviour would be to count grapheme clusters, but this behaviour is notoriously inconsistent between languages. So the best solution in our case is to use the utf8-encoded bytes length, to ensure consistency between all implementations.

You're welcome to open a PR to clarify this with the consistency rationale, else I'll do it in the upcoming days.

**Comment by yaronf** [comment]
https://github.com/biscuit-auth/biscuit/pull/159
