### ISSUE TITLE
adding serializing method or a print function to sealed biscuit

### ISSUE THREAD

**Issue by mohamedrajhi** [biscuit-auth/biscuit#39]
Hello , i work on some use cases using biscuit web token and i would like to use the feature sealed biscuit but i have a problem with that , after calling the feature used to seal the biscuit i can not print or serialize the result.

do you have any suggestions for this ?

**Comment by Geal** [comment]
@mohamedrajhi which version are you using, Rust or Java?

**Comment by mohamedrajhi** [comment]
@Geal i'm using rust

**Comment by Geal** [comment]
so there was already a method for this, could you show me the code you're using?

**Comment by divarvel** [comment]
This is a library matter, not related to the specification itself.
