### ISSUE TITLE
Using the symbol table for strings too

### ISSUE THREAD

**Issue by Geal** [biscuit-auth/biscuit#58]
The difference between strings and symbols can be confusing, because there are special symbols, `#authority` and `#ambient`, and normal symbols that can be user defined. Those are just be considered as special strings with limited constraints checks, and a bit faster to compare since they're actually stored as an index in the symbols table.
I'd propose that we store all strings in the symbol tables (this can reduce storage size as strings tend to be repeated) and reserve the symbol type to reserved symbols (only `#authority` and `#ambient` for now).
This would require that the Datalog engine accesses the symbol table during execution (for string constraints checks)

**Comment by meh** [comment]
Seems reasonable, have you also considered compression a la DNS?

It'd likely save space with paths, domains and such, at no cost.

**Comment by Geal** [comment]
it might make he format a lot more complex though. Symbol tables already come with a high complexity budget, since they must support adding strings at each new block

**Comment by Geal** [comment]
v2 now uses the symbol table for strings https://github.com/biscuit-auth/biscuit/issues/72
