### ISSUE TITLE
new text syntax

### ISSUE THREAD

**Issue by Geal** [biscuit-auth/biscuit#60]
I'm simplifying the text syntax, but it can still be a bit confusing, so I'd lie to propose a different version, that's further from traditional datalog syntax.
I'd like to change from:
```
right(#authority, $1, #read) <- resource(#ambient, $1), owner(#ambient, $0, $1)
```
to 
```
right(#authority, $1, #read) if resource(#ambient, $1) and owner(#ambient, $0, $1)
```
with `if` and `and` case insensitive, so we can write `right(#authority, $1, #read) IF resource(#ambient, $1) AND owner(#ambient, $0, $1)` if it's easier to read without text highlighting

And for caveats:
```
caveat1($0, $1) <- right(#authority, $0, $1), resource(#ambient, $0), operation(#ambient, $1)
```
to
``` 
check right(#authority, $0, $1) and resource(#ambient, $0) and operation(#ambient, $1)
```
or another keyword, like `verify`, `satisfy`, `ensures`, `assert`, etc

For constraints, instead of moving them to the end like this:
```
valid_date("file1") <- time(#ambient, $0 ), resource(#ambient, "file1") @ $0 <= 2019-12-04T09:46:41+00:00
```

we would write:
```
valid_date("file1") if time(#ambient, $0 ) and resource(#ambient, "file1") and $0 <= 2019-12-04T09:46:41+00:00
```
And constraints could be anywhere in the rule's body, like this:
```
valid_date("file1") if time(#ambient, $0 ) and $0 <= 2019-12-04T09:46:41+00:00 and resource(#ambient, "file1")
```

**Comment by meh** [comment]
I also prefer the current syntax.

**Comment by Geal** [comment]
v2 now has a new syntax with a defined grammar https://github.com/biscuit-auth/biscuit/issues/72
