### ISSUE TITLE
Serialized errors in samples

### ISSUE THREAD

**Issue by divarvel** [biscuit-auth/biscuit#84]
The v2 samples carry a lot of structured information, which is super useful for conformance tests.

Sadly, the errors are for now just text rendering of rust errors. It would be great to have them in structured JSON so that implementations can check expected errors as well.

**Comment by Geal** [comment]
errors are serialized now https://github.com/biscuit-auth/biscuit/commit/2d2e03ff0951f7d51196031a1d5e346682f5d358
