### ISSUE TITLE
Isolated block execution

### ISSUE THREAD

**Issue by divarvel** [biscuit-auth/biscuit#86]
In biscuit v2.0, blocks are interpreted in order. This means that a block cannot pollute previous blocks with its facts, but can have its facts accessed by the following blocks.

With this system, it's not possible to make a token capabilities _grow_, but it can be used to _prevent further restriction_ of a token capabilities, in a way that's not immediately obvious.

Consider this small example: given an open token, adding `time(9999-01-01T00:00:00Z);`.
This will not affect already existing TTL checks, but will effectively prevent further TTL checks from working as expected. This is especially bad in contexts where checks are added automatically, since it would be possible to erroneously think that a newly added check works as expected.

# Possible solutions

1. completely prevent facts and rules from appearing in blocks that are not the authority block (this is an existing option in the haskell lib, for instance)
2. execute each block in isolation so that facts defined in a block are not visible anywhere else

I'm not satisfied with the current situation since it prevents from making any assumption about block checks without inspecting the whole token. Solution 1. is both underwhelming (it would be opt-in) and overwhelming (defining facts in a block would be useful for complex checks). Solution 2. sounds good to me, but would prevent some use cases, but depending on a previous block's check seems dangerous in any case, since only the authority block can be trusted.

**Comment by zarutian** [comment]
Hmm... perhaps a way to explictly refer to facts defined/derived in previous blocks in combination with solution 2 could be the third solution?

**Comment by clementd-fretlink** [comment]
so if i understand correctly, the default would be "only see facts produced by the authority, verifier and current block", and a special keyword (for instance), would make a check operate on those facts + the facts of the previous block?

**Comment by zarutian** [comment]
I was thinking more of an spefic fact import mechanism.
Like 'import Foo facts from just the second block' kind of thing.
That way one could compose a new block that checks for the facts produced by authority, verifier, the current block, and spefic facts from other prior blocks. This allows for blocks with 'nonsense facts' (alt-facts?) to be ignored while using other facts from that same blocks.

**Comment by divarvel** [comment]
Oh, that could play well with an idea I have for mimicking 3rd party caveats: allowing blocks to be signed with an extra secret key. In datalog we could add: `trust blocks from hex:<public_key>` to add facts and blocks from the relevant pks.

**Comment by Geal** [comment]
IIRC one of the use cases was in making a token that would not be valid until specific data appear. Ex: the first or second block has a check requiring the presence of a block signed by a revocation oracle. Until the token is attenuated with data from such an oracle, it will not be usable. That was one of the motivations behind the "check after" idea

**Comment by divarvel** [comment]
- Having a per-block marker is interesting because it would apply to rules and checks (but makes granular checks more cumbersome)
- Having a scope descriptor `authority | previous (current behaviour) | blocks signed with <private key set>` handles both this use case and 3rd party caveats

**Comment by divarvel** [comment]
The last biscuit v2 update changed the default to trusting only current + authority block.

3rd party blocks will supersede scope descriptors (see #88 )
