### ISSUE TITLE
biscuitsec.org Down

### ISSUE THREAD

**Issue by grempe** [biscuit-auth/biscuit#89]
The playground website seems to be down:

https://biscuitsec.org/

**Comment by Geal** [comment]
It works on https://www.biscuitsec.org/
I messed up the redirections somehow

**Comment by grempe** [comment]
www still works fine. But the bare domain still does not. 

https://biscuitsec.org

**Comment by Geal** [comment]
the bare domain is fixed now. There was a redirection issue
